[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
rust_decimal = { version = "1", features = ["serde-arbitrary-precision"] }
rayon = "1"
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
