"""Advisory extension rules E001 to E005 and E101 to E103.

Same design as the official engine (yara_engine.py): each eXXX_details(view, catalogue, history) is the single source of truth for
its rule and returns the fact-tag lines, the evidence paths, the affected line ids and the message from one pass over the claim; a
YARA-X pack matches the combined blob. The pack is generated by pack_source() and committed as rules/extensions.yar, and a test
keeps the two identical. Nothing here is imported by, or changes, the official engine: extension results have their own schema,
their own ids and never enter the official fifteen.

Status semantics follow the official engine: a missing input gives UNABLE_TO_ASSESS (never PASS), an absent trigger gives
NOT_APPLICABLE, and an exception inside one rule gives UNABLE_TO_ASSESS for that rule only.
"""
import hashlib
import json
import logging
import re
import threading
from decimal import Decimal, InvalidOperation
from pathlib import Path

import yara_x

from engine_core import pointer
from facts_extractor import _q, rule_view, valid_date

logger = logging.getLogger('extension_rules')

ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = ROOT / 'rules' / 'extensions.yar'
CATALOGUE_PATH = ROOT / 'rules' / 'extensions' / 'catalogue.json'
PRECEDENCE = ['FAIL', 'UNABLE_TO_ASSESS', 'NOT_APPLICABLE', 'PASS']
_OUTCOMES = (('FAIL', '/{rid}:FAIL:/'), ('PASS', '"{rid}:OK"'), ('UNABLE_TO_ASSESS', '"{rid}:UNKNOWN"'), ('NOT_APPLICABLE', '"{rid}:NA"'))

_catalogue = None
_limits = None
_compiled = None
_LOCK = threading.RLock()


class ExtensionEngineError(Exception):
    pass


def load_catalogue():
    global _catalogue
    with _LOCK:
        if _catalogue is None:
            _catalogue = json.loads(CATALOGUE_PATH.read_text(encoding='utf-8'))
        return _catalogue


def pack_source():
    cat = load_catalogue()
    blocks = []
    for r in cat['rules']:
        for outcome, pattern in _OUTCOMES:
            blocks.append(
                f'rule {r["rule_id"]}_{outcome.lower()} {{\n  meta:\n    rule_id = "{r["rule_id"]}"\n    outcome = "{outcome}"\n'
                f'    severity = "{r["severity"]}"\n    rule_version = "{r["version"]}"\n  strings:\n    $m = {pattern.format(rid=r["rule_id"])}\n'
                f'  condition:\n    $m\n}}\n')
    return '\n'.join(blocks)


def pack_hash():
    return hashlib.sha256(pack_source().encode('utf-8')).hexdigest()


def _compiled_rules():
    global _compiled
    with _LOCK:
        if _compiled is None:
            _compiled = yara_x.compile(pack_source())
        return _compiled


def _lines(view):
    rows = view.get('lines') if isinstance(view, dict) else None
    return [(i, r) for i, r in enumerate(rows) if isinstance(r, dict)] if isinstance(rows, list) else []


def _line_id(row):
    return row['line_id'] if isinstance(row.get('line_id'), str) and row['line_id'] else None


def _text(value):
    return value if isinstance(value, str) else ''


def _unknown(rid, message):
    return {'facts': [f'{rid}:UNKNOWN'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': message}


def _na(rid, message):
    return {'facts': [f'{rid}:NA'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': message}


def _line_paths(i, *names):
    return [f'/lines/{i}/{n}' for n in names]


# ---------------------------------------------------------------------------------------------------------- E001, E002
def _pair_scan(view, cat):
    """For every catalogue pair whose two codes both appear in the claim: the same-date combinations, and whether any line of the
    pair has a date that cannot be read (then the result for that pair is unknown)."""
    lines = _lines(view)
    found = []
    for pair in cat['pairs']:
        prim = [(i, r) for i, r in lines if r.get('service_code') == pair['primary']]
        sec = [(i, r) for i, r in lines if r.get('service_code') == pair['secondary']]
        if not prim or not sec:
            continue
        unreadable = any(valid_date(r.get('service_date')) is None for _, r in prim + sec)
        combos = [(pi, si) for pi, pr in prim for si, sr in sec
                  if valid_date(pr.get('service_date')) is not None and valid_date(pr.get('service_date')) == valid_date(sr.get('service_date'))]
        found.append({'pair': pair, 'combos': combos, 'unreadable': unreadable, 'rows': dict(lines)})
    return found


def _modifier_is_exception(row, cat):
    return row.get('modifier') in cat['exception_modifiers']


def _pair_result(rid, view, cat, only_never, violation):
    found = [f for f in _pair_scan(view, cat) if not only_never or not f['pair']['modifier_allowed']]
    if not found:
        return _na(rid, 'No listed procedure pair is present on this claim.')
    facts, paths, ids, idx = [], [], [], []
    for f in found:
        for pi, si in f['combos']:
            sec_row = f['rows'][si]
            if violation(f['pair'], sec_row):
                facts.append(f'{rid}:FAIL:{pi},{si}:pair={_q(f["pair"]["primary"])}|{_q(f["pair"]["secondary"])}')
                idx += [pi, si]
    unreadable = any(f['unreadable'] for f in found)
    if unreadable:
        facts.append(f'{rid}:UNKNOWN')
    for i in sorted(set(idx)):
        row = found[0]['rows'][i]
        paths += _line_paths(i, 'service_code', 'service_date', 'modifier')
        if _line_id(row):
            ids.append(_line_id(row))
    if any(x.startswith(f'{rid}:FAIL:') for x in facts):
        return {'facts': facts, 'evidence_paths': paths, 'line_ids': list(dict.fromkeys(ids)), 'message': MESSAGES[rid]}
    if unreadable:
        return {'facts': facts, 'evidence_paths': _unreadable_paths(found), 'line_ids': [],
                'message': 'A line of a listed pair has no readable service date, so the check could not be completed.'}
    return {'facts': [f'{rid}:OK'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': PASS_MESSAGES[rid]}


def _unreadable_paths(found):
    paths = []
    for f in found:
        for i, r in f['rows'].items():
            if r.get('service_code') in (f['pair']['primary'], f['pair']['secondary']):
                paths += _line_paths(i, 'service_code', 'service_date')
    return list(dict.fromkeys(paths))


def e001_details(view, cat, history):
    return _pair_result('E001', view, cat, False, lambda pair, sec: not _modifier_is_exception(sec, cat))


def e002_details(view, cat, history):
    return _pair_result('E002', view, cat, True, lambda pair, sec: _modifier_is_exception(sec, cat))


MESSAGES = {
    'E001': 'Two services that form a listed pair were billed on the same date without an exception modifier on the component.',
    'E002': 'An exception modifier was used on a pair that does not allow one to separate its services.',
}
PASS_MESSAGES = {
    'E001': 'Listed pairs are not billed together on one date, or the component carries an exception modifier.',
    'E002': 'No exception modifier is used on a pair that forbids one.',
}


# ---------------------------------------------------------------------------------------------------- E003, E004, E005
_EVENT_DATE = re.compile(r'Event date: ?([0-9]{4}-[0-9]{2}-[0-9]{2})(?![0-9])')


def _diagnosis(view):
    dx = view.get('diagnosis_code')
    return dx if isinstance(dx, str) and dx else None


def e003_details(view, cat, history):
    dx = _diagnosis(view)
    if dx is None:
        return _unknown('E003', 'The claim has no readable diagnosis code, so the event-date requirement could not be checked.')
    if not cat['diagnoses'].get(dx, {}).get('requires_event_date'):
        return _na('E003', 'This diagnosis does not require an event date.')
    service_dates = [d for d in (valid_date(r.get('service_date')) for _, r in _lines(view)) if d is not None]
    if not service_dates:
        return {'facts': ['E003:UNKNOWN'], 'evidence_paths': ['/diagnosis_code'], 'line_ids': [],
                'message': 'No line has a readable service date, so the event date could not be compared with it.'}
    sources = [('/notes', view.get('notes'))] + [(f'/attachments/{i}/text', r.get('text')) for i, r in enumerate(view.get('attachments') or [])
                                               if isinstance(r, dict)]
    events, paths = [], ['/diagnosis_code']
    for path, text in sources:
        found = [valid_date(m) for m in _EVENT_DATE.findall(text)] if isinstance(text, str) else []
        found = [d for d in found if d is not None]
        if found:
            events += found
            paths.append(path)
    if any(d <= min(service_dates) for d in events):
        return {'facts': ['E003:OK'], 'evidence_paths': paths, 'line_ids': [], 'message': 'An event date on or before the first service is stated.'}
    return {'facts': [f'E003:FAIL:dx={_q(dx)}'], 'evidence_paths': paths + [f'/lines/{i}/service_date' for i, _ in _lines(view)][:1],
            'line_ids': [], 'message': 'This diagnosis requires an event date (written "Event date: YYYY-MM-DD") on or before the first service date, and none was found.'}


def e004_details(view, cat, history):
    codes = {code for code, s in cat['services'].items() if s.get('category') == 'pharmaceutical'}
    rx = [(i, r) for i, r in _lines(view) if r.get('service_code') in codes]
    if not rx:
        return _na('E004', 'No pharmaceutical line from the extension catalogue is present.')
    bad = [(i, r) for i, r in rx if r.get('modifier') not in cat['route_modifiers']]
    if not bad:
        return {'facts': ['E004:OK'], 'evidence_paths': [p for i, _ in rx for p in _line_paths(i, 'service_code', 'modifier')],
                'line_ids': [], 'message': 'Every pharmaceutical line carries a route-of-administration modifier.'}
    return {'facts': [f'E004:FAIL:{i}' for i, _ in bad], 'evidence_paths': [p for i, _ in bad for p in _line_paths(i, 'service_code', 'modifier')],
            'line_ids': [_line_id(r) for _, r in bad if _line_id(r)],
            'message': 'A pharmaceutical line has no valid route-of-administration modifier.'}


def e005_details(view, cat, history):
    dx = _diagnosis(view)
    if dx is None:
        return _unknown('E005', 'The claim has no readable diagnosis code, so its position could not be checked.')
    if cat['diagnoses'].get(dx, {}).get('secondary_only'):
        return {'facts': [f'E005:FAIL:dx={_q(dx)}'], 'evidence_paths': ['/diagnosis_code'], 'line_ids': [],
                'message': 'The header diagnosis is reserved for a secondary position and cannot be the primary reason for the claim.'}
    return {'facts': ['E005:OK'], 'evidence_paths': ['/diagnosis_code'], 'line_ids': [],
            'message': 'The header diagnosis may be used as the primary diagnosis.'}


# ---------------------------------------------------------------------------------------------------- E101, E102, E103
NO_HISTORY = 'Claim history is not available, so earlier claims could not be checked.'


def _num(value):
    """A finite number, or None. Booleans are not quantities."""
    if isinstance(value, bool) or not isinstance(value, (int, float, Decimal)):
        return None
    try:
        d = Decimal(str(value))
    except InvalidOperation:
        return None
    return d if d.is_finite() else None


def _official_limits():
    global _limits
    with _LOCK:
        if _limits is None:
            services = json.loads((ROOT / 'rules' / 'services.json').read_text(encoding='utf-8'))
            _limits = {code: Decimal(str(v['max_quantity'])) for code, v in services.items()}
        return _limits


def _earlier_views(view, history):
    """The earlier claims as cleaned views. A history that answers with anything but a list of claim dicts is a broken store: raise,
    so the history rules become UNABLE_TO_ASSESS instead of reading garbage as "no earlier claims"."""
    rows = history.earlier_claims(view)
    if not isinstance(rows, (list, tuple)) or not all(isinstance(r, dict) for r in rows):
        raise ExtensionEngineError('claim history returned data that is not a list of claims')
    return [rule_view(r) for r in rows]


def _party(view):
    patient, provider = view.get('patient_id'), view.get('provider_id')
    return provider if isinstance(patient, str) and patient and isinstance(provider, str) and provider else None


def _line_key(row):
    code, day, qty, net = row.get('service_code'), valid_date(row.get('service_date')), _num(row.get('quantity')), _num(row.get('net_amount'))
    if not isinstance(code, str) or not code or day is None or qty is None or net is None:
        return None
    return code, day, qty, net


def e101_details(view, cat, history):
    if history is None:
        return _unknown('E101', NO_HISTORY)
    provider = _party(view)
    if provider is None:
        return _unknown('E101', 'The claim has no readable patient or provider, so earlier claims could not be matched.')
    seen = set()
    for prev in _earlier_views(view, history):
        if prev.get('provider_id') == provider:
            seen.update(k for k in (_line_key(r) for _, r in _lines(prev)) if k is not None)
    facts, paths, ids, unreadable = [], [], [], False
    for i, row in _lines(view):
        key = _line_key(row)
        if key is None:
            unreadable = True
        elif key in seen:
            facts.append(f'E101:FAIL:{i}')
            paths += _line_paths(i, 'service_code', 'service_date', 'quantity', 'net_amount')
            if _line_id(row):
                ids.append(_line_id(row))
    if unreadable:
        facts.append('E101:UNKNOWN')
    if any(f.startswith('E101:FAIL:') for f in facts):
        return {'facts': facts, 'evidence_paths': paths, 'line_ids': ids,
                'message': 'A line is identical (patient, provider, service, date, quantity and amount) to a line of an earlier claim.'}
    if unreadable:
        return {'facts': facts, 'evidence_paths': ['/claim_id'], 'line_ids': [],
                'message': 'A line has an unreadable service, date, quantity or amount, so it could not be compared with earlier claims.'}
    return {'facts': ['E101:OK'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': 'No line repeats a line of an earlier claim.'}


def e102_details(view, cat, history):
    groups = {}
    for i, row in _lines(view):
        aid = row.get('authorization_id')
        if isinstance(aid, str) and aid:
            groups.setdefault(aid, []).append((i, row))
    if not groups:
        return _na('E102', 'No line references an authorization.')
    if history is None:
        return _unknown('E102', NO_HISTORY)
    records = {}
    for k, a in enumerate(view.get('authorizations') or []):
        if isinstance(a, dict) and isinstance(a.get('authorization_id'), str):
            records.setdefault(a['authorization_id'], (k, a))
    earlier = _earlier_views(view, history)
    facts, paths, ids, unreadable = [], [], [], False
    for aid, rows in groups.items():
        k, rec = records.get(aid, (None, None))
        limit = _num(rec.get('max_quantity')) if rec else None
        used = [_num(r.get('quantity')) for _, r in rows]
        for prev in earlier:
            used += [_num(r.get('quantity')) for _, r in _lines(prev) if r.get('authorization_id') == aid]
        if limit is None or any(u is None for u in used):
            unreadable = True
        elif sum(used) > limit:
            facts.append(f'E102:FAIL:{_q(aid)}')
            for i, r in rows:
                paths += _line_paths(i, 'authorization_id', 'quantity')
                if _line_id(r):
                    ids.append(_line_id(r))
            paths.append(f'/authorizations/{k}/max_quantity')
    if unreadable:
        facts.append('E102:UNKNOWN')
    if any(f.startswith('E102:FAIL:') for f in facts):
        return {'facts': facts, 'evidence_paths': paths, 'line_ids': list(dict.fromkeys(ids)),
                'message': 'Units under this authorization in earlier claims plus this claim exceed its approved maximum.'}
    if unreadable:
        return {'facts': facts, 'evidence_paths': ['/claim_id'], 'line_ids': [],
                'message': 'An authorization record, its maximum, or a quantity is missing or unreadable, so the total could not be checked.'}
    return {'facts': ['E102:OK'], 'evidence_paths': ['/claim_id'], 'line_ids': [],
            'message': 'Units under every referenced authorization stay within its approved maximum.'}


def e103_details(view, cat, history):
    limits = _official_limits()
    groups, unreadable = {}, False
    for i, row in _lines(view):
        code = row.get('service_code')
        if code not in limits:
            continue
        day, qty = valid_date(row.get('service_date')), _num(row.get('quantity'))
        if day is None or qty is None:
            unreadable = True
            continue
        groups.setdefault((code, day), []).append((i, row, qty))
    if not groups and not unreadable:
        return _na('E103', 'No line uses a service with a daily limit.')
    if history is None:
        return _unknown('E103', NO_HISTORY)
    provider = _party(view)
    if provider is None:
        return _unknown('E103', 'The claim has no readable patient or provider, so earlier claims could not be matched.')
    earlier_units = {}
    for prev in _earlier_views(view, history):
        if prev.get('provider_id') != provider:
            continue
        for _, r in _lines(prev):
            code, day, qty = r.get('service_code'), valid_date(r.get('service_date')), _num(r.get('quantity'))
            if code in limits and day is not None and qty is not None:
                earlier_units[(code, day)] = earlier_units.get((code, day), Decimal(0)) + qty
    facts, paths, ids = [], [], []
    for (code, day), rows in groups.items():
        before = earlier_units.get((code, day), Decimal(0))
        if before > 0 and before + sum(q for _, _, q in rows) > limits[code]:
            facts.append(f'E103:FAIL:{_q(code)}:{day.isoformat()}')
            for i, r, _ in rows:
                paths += _line_paths(i, 'service_code', 'service_date', 'quantity')
                if _line_id(r):
                    ids.append(_line_id(r))
    if unreadable:
        facts.append('E103:UNKNOWN')
    if any(f.startswith('E103:FAIL:') for f in facts):
        return {'facts': facts, 'evidence_paths': paths, 'line_ids': ids,
                'message': 'Units of this service on this date for this patient and provider, in earlier claims plus this claim, exceed the daily limit.'}
    if unreadable:
        return {'facts': facts, 'evidence_paths': ['/claim_id'], 'line_ids': [],
                'message': 'A line has an unreadable date or quantity, so the daily total could not be checked.'}
    return {'facts': ['E103:OK'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': 'Daily totals across claims stay within each service limit.'}


def _pending(rid):
    return lambda view, cat, history: _unknown(rid, 'This check is not built yet.')


DETAIL_FUNCS = {
    'E001': e001_details, 'E002': e002_details, 'E003': e003_details, 'E004': e004_details, 'E005': e005_details,
    'E101': e101_details, 'E102': e102_details, 'E103': e103_details,
}


# ---------------------------------------------------------------------------------------------------------- assembly
def _safe_evidence(c, paths):
    out = []
    for p in dict.fromkeys(paths):
        try:
            out.append({'path': p, 'value': pointer(c, p)})
        except (KeyError, IndexError, TypeError, ValueError):
            continue
    return out or [{'path': '/claim_id', 'value': c.get('claim_id') if isinstance(c, dict) else None}]


def evaluate_extensions(c, history=None, tool_errors=None, cat=None):
    """The eight advisory results for one claim. Never raises for a dict claim: a failure inside one rule makes that rule
    UNABLE_TO_ASSESS and is appended to tool_errors."""
    cat = cat or load_catalogue()
    try:
        view = rule_view(c)
    except Exception as e:  # noqa: BLE001 - a malformed claim must still get eight results
        view = {}
        if tool_errors is not None:
            tool_errors.append(f'claim view: {type(e).__name__}: {e}')
    details, crashed = {}, {}
    for rid, fn in DETAIL_FUNCS.items():
        try:
            details[rid] = fn(view, cat, history)
        except Exception as e:  # noqa: BLE001 - isolation is the point
            crashed[rid] = f'{type(e).__name__}: {e}'
            logger.warning('extension rule %s crashed, treating as UNABLE_TO_ASSESS: %r', rid, crashed[rid])
            if tool_errors is not None:
                tool_errors.append(f'{rid}: engine exception {crashed[rid]}')
    blob = '\n'.join(fact for d in details.values() for fact in d['facts']) + '\n'
    rules = _compiled_rules()
    with _LOCK:
        scan = rules.scan(blob.encode('utf-8'))
        matched = [(dict(r.metadata)['rule_id'], dict(r.metadata)['outcome']) for r in scan.matching_rules]
    by_rule = {}
    for rid, outcome in matched:
        by_rule.setdefault(rid, set()).add(outcome)
    defs = {r['rule_id']: r for r in cat['rules']}
    phash = pack_hash()
    claim_id = c.get('claim_id') if isinstance(c, dict) and isinstance(c.get('claim_id'), str) else ''
    results = []
    for rid in DETAIL_FUNCS:
        r = defs[rid]
        if rid in crashed:
            status, d = 'UNABLE_TO_ASSESS', {'line_ids': [], 'evidence_paths': ['/claim_id'],
                                             'message': 'An internal error prevented this check; it is treated as unable to assess.'}
        else:
            outcomes = by_rule.get(rid, set())
            if not outcomes:
                raise ExtensionEngineError(f'{rid} produced no outcome - extractor and rule pack are out of sync')
            status, d = next(o for o in PRECEDENCE if o in outcomes), details[rid]
        results.append({
            'claim_id': claim_id, 'rule_id': rid, 'rule_version': r['version'], 'status': status, 'severity': r['severity'],
            'affected_line_ids': d['line_ids'], 'evidence': _safe_evidence(c, d['evidence_paths']), 'rule_source': r['source'],
            'explanation': d['message'], 'corrective_action': r['corrective_action'] if status in ('FAIL', 'UNABLE_TO_ASSESS') else '',
            'confidence': None, 'confidence_kind': 'not_probabilistic', 'requires_human_review': status in ('FAIL', 'UNABLE_TO_ASSESS'),
            'method': 'deterministic', 'review_status': 'unreviewed', 'rule_family': 'extension', 'advisory': True, 'pack_hash': phash,
        })
    return results
