"""Advisory extension rules E001 to E005 and E101 to E103.

Same design as the official engine (yara_engine.py): each eXXX_details(view, catalogue, history) is the single source of truth for
its rule and returns the fact-tag lines, the evidence paths, the affected line ids and the message from one pass over the claim; a
YARA-X pack matches the combined blob. The pack is generated by pack_source() and committed as rules/extensions.yar, and a test
keeps the two identical. Nothing here is imported by, or changes, the official engine: extension results have their own schema,
their own ids and never enter the official fifteen.

Status semantics follow the official engine: a missing input gives UNABLE_TO_ASSESS (never PASS), an absent trigger gives
NOT_APPLICABLE, and an exception inside one rule gives UNABLE_TO_ASSESS for that rule only.
"""
import hashlib
import json
import logging
import threading
from pathlib import Path

import yara_x

from engine_core import pointer
from facts_extractor import _q, rule_view, valid_date

logger = logging.getLogger('extension_rules')

ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = ROOT / 'rules' / 'extensions.yar'
CATALOGUE_PATH = ROOT / 'rules' / 'extensions' / 'catalogue.json'
PRECEDENCE = ['FAIL', 'UNABLE_TO_ASSESS', 'NOT_APPLICABLE', 'PASS']
_OUTCOMES = (('FAIL', '/{rid}:FAIL:/'), ('PASS', '"{rid}:OK"'), ('UNABLE_TO_ASSESS', '"{rid}:UNKNOWN"'), ('NOT_APPLICABLE', '"{rid}:NA"'))

_catalogue = None
_compiled = None
_LOCK = threading.RLock()


class ExtensionEngineError(Exception):
    pass


def load_catalogue():
    global _catalogue
    with _LOCK:
        if _catalogue is None:
            _catalogue = json.loads(CATALOGUE_PATH.read_text(encoding='utf-8'))
        return _catalogue


def pack_source():
    cat = load_catalogue()
    blocks = []
    for r in cat['rules']:
        for outcome, pattern in _OUTCOMES:
            blocks.append(
                f'rule {r["rule_id"]}_{outcome.lower()} {{\n  meta:\n    rule_id = "{r["rule_id"]}"\n    outcome = "{outcome}"\n'
                f'    severity = "{r["severity"]}"\n    rule_version = "{r["version"]}"\n  strings:\n    $m = {pattern.format(rid=r["rule_id"])}\n'
                f'  condition:\n    $m\n}}\n')
    return '\n'.join(blocks)


def pack_hash():
    return hashlib.sha256(pack_source().encode('utf-8')).hexdigest()


def _compiled_rules():
    global _compiled
    with _LOCK:
        if _compiled is None:
            _compiled = yara_x.compile(pack_source())
        return _compiled


def _lines(view):
    rows = view.get('lines') if isinstance(view, dict) else None
    return [(i, r) for i, r in enumerate(rows) if isinstance(r, dict)] if isinstance(rows, list) else []


def _line_id(row):
    return row['line_id'] if isinstance(row.get('line_id'), str) and row['line_id'] else None


def _text(value):
    return value if isinstance(value, str) else ''


def _unknown(rid, message):
    return {'facts': [f'{rid}:UNKNOWN'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': message}


def _na(rid, message):
    return {'facts': [f'{rid}:NA'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': message}


def _line_paths(i, *names):
    return [f'/lines/{i}/{n}' for n in names]


# ---------------------------------------------------------------------------------------------------------- E001, E002
def _pair_scan(view, cat):
    """For every catalogue pair whose two codes both appear in the claim: the same-date combinations, and whether any line of the
    pair has a date that cannot be read (then the result for that pair is unknown)."""
    lines = _lines(view)
    found = []
    for pair in cat['pairs']:
        prim = [(i, r) for i, r in lines if r.get('service_code') == pair['primary']]
        sec = [(i, r) for i, r in lines if r.get('service_code') == pair['secondary']]
        if not prim or not sec:
            continue
        unreadable = any(valid_date(r.get('service_date')) is None for _, r in prim + sec)
        combos = [(pi, si) for pi, pr in prim for si, sr in sec
                  if valid_date(pr.get('service_date')) is not None and valid_date(pr.get('service_date')) == valid_date(sr.get('service_date'))]
        found.append({'pair': pair, 'combos': combos, 'unreadable': unreadable, 'rows': dict(lines)})
    return found


def _modifier_is_exception(row, cat):
    return row.get('modifier') in cat['exception_modifiers']


def _pair_result(rid, view, cat, only_never, violation):
    found = [f for f in _pair_scan(view, cat) if not only_never or not f['pair']['modifier_allowed']]
    if not found:
        return _na(rid, 'No listed procedure pair is present on this claim.')
    facts, paths, ids, idx = [], [], [], []
    for f in found:
        for pi, si in f['combos']:
            sec_row = f['rows'][si]
            if violation(f['pair'], sec_row):
                facts.append(f'{rid}:FAIL:{pi},{si}:pair={_q(f["pair"]["primary"])}|{_q(f["pair"]["secondary"])}')
                idx += [pi, si]
    unreadable = any(f['unreadable'] for f in found)
    if unreadable:
        facts.append(f'{rid}:UNKNOWN')
    for i in sorted(set(idx)):
        row = found[0]['rows'][i]
        paths += _line_paths(i, 'service_code', 'service_date', 'modifier')
        if _line_id(row):
            ids.append(_line_id(row))
    if any(x.startswith(f'{rid}:FAIL:') for x in facts):
        return {'facts': facts, 'evidence_paths': paths, 'line_ids': list(dict.fromkeys(ids)), 'message': MESSAGES[rid]}
    if unreadable:
        return {'facts': facts, 'evidence_paths': _unreadable_paths(found), 'line_ids': [],
                'message': 'A line of a listed pair has no readable service date, so the check could not be completed.'}
    return {'facts': [f'{rid}:OK'], 'evidence_paths': ['/claim_id'], 'line_ids': [], 'message': PASS_MESSAGES[rid]}


def _unreadable_paths(found):
    paths = []
    for f in found:
        for i, r in f['rows'].items():
            if r.get('service_code') in (f['pair']['primary'], f['pair']['secondary']):
                paths += _line_paths(i, 'service_code', 'service_date')
    return list(dict.fromkeys(paths))


def e001_details(view, cat, history):
    return _pair_result('E001', view, cat, False, lambda pair, sec: not _modifier_is_exception(sec, cat))


def e002_details(view, cat, history):
    return _pair_result('E002', view, cat, True, lambda pair, sec: _modifier_is_exception(sec, cat))


MESSAGES = {
    'E001': 'Two services that form a listed pair were billed on the same date without an exception modifier on the component.',
    'E002': 'An exception modifier was used on a pair that does not allow one to separate its services.',
}
PASS_MESSAGES = {
    'E001': 'Listed pairs are not billed together on one date, or the component carries an exception modifier.',
    'E002': 'No exception modifier is used on a pair that forbids one.',
}


def _pending(rid):
    return lambda view, cat, history: _unknown(rid, 'This check is not built yet.')


DETAIL_FUNCS = {
    'E001': e001_details, 'E002': e002_details, 'E003': _pending('E003'), 'E004': _pending('E004'), 'E005': _pending('E005'),
    'E101': _pending('E101'), 'E102': _pending('E102'), 'E103': _pending('E103'),
}


# ---------------------------------------------------------------------------------------------------------- assembly
def _safe_evidence(c, paths):
    out = []
    for p in dict.fromkeys(paths):
        try:
            out.append({'path': p, 'value': pointer(c, p)})
        except (KeyError, IndexError, TypeError, ValueError):
            continue
    return out or [{'path': '/claim_id', 'value': c.get('claim_id') if isinstance(c, dict) else None}]


def evaluate_extensions(c, history=None, tool_errors=None, cat=None):
    """The eight advisory results for one claim. Never raises for a dict claim: a failure inside one rule makes that rule
    UNABLE_TO_ASSESS and is appended to tool_errors."""
    cat = cat or load_catalogue()
    try:
        view = rule_view(c)
    except Exception as e:  # noqa: BLE001 - a malformed claim must still get eight results
        view = {}
        if tool_errors is not None:
            tool_errors.append(f'claim view: {type(e).__name__}: {e}')
    details, crashed = {}, {}
    for rid, fn in DETAIL_FUNCS.items():
        try:
            details[rid] = fn(view, cat, history)
        except Exception as e:  # noqa: BLE001 - isolation is the point
            crashed[rid] = f'{type(e).__name__}: {e}'
            logger.warning('extension rule %s crashed, treating as UNABLE_TO_ASSESS: %r', rid, crashed[rid])
            if tool_errors is not None:
                tool_errors.append(f'{rid}: engine exception {crashed[rid]}')
    blob = '\n'.join(fact for d in details.values() for fact in d['facts']) + '\n'
    rules = _compiled_rules()
    with _LOCK:
        scan = rules.scan(blob.encode('utf-8'))
        matched = [(dict(r.metadata)['rule_id'], dict(r.metadata)['outcome']) for r in scan.matching_rules]
    by_rule = {}
    for rid, outcome in matched:
        by_rule.setdefault(rid, set()).add(outcome)
    defs = {r['rule_id']: r for r in cat['rules']}
    phash = pack_hash()
    claim_id = c.get('claim_id') if isinstance(c, dict) and isinstance(c.get('claim_id'), str) else ''
    results = []
    for rid in DETAIL_FUNCS:
        r = defs[rid]
        if rid in crashed:
            status, d = 'UNABLE_TO_ASSESS', {'line_ids': [], 'evidence_paths': ['/claim_id'],
                                             'message': 'An internal error prevented this check; it is treated as unable to assess.'}
        else:
            outcomes = by_rule.get(rid, set())
            if not outcomes:
                raise ExtensionEngineError(f'{rid} produced no outcome - extractor and rule pack are out of sync')
            status, d = next(o for o in PRECEDENCE if o in outcomes), details[rid]
        results.append({
            'claim_id': claim_id, 'rule_id': rid, 'rule_version': r['version'], 'status': status, 'severity': r['severity'],
            'affected_line_ids': d['line_ids'], 'evidence': _safe_evidence(c, d['evidence_paths']), 'rule_source': r['source'],
            'explanation': d['message'], 'corrective_action': r['corrective_action'] if status in ('FAIL', 'UNABLE_TO_ASSESS') else '',
            'confidence': None, 'confidence_kind': 'not_probabilistic', 'requires_human_review': status in ('FAIL', 'UNABLE_TO_ASSESS'),
            'method': 'deterministic', 'review_status': 'unreviewed', 'rule_family': 'extension', 'advisory': True, 'pack_hash': phash,
        })
    return results
